"""init

Revision ID: 24bc4ea98b96
Revises: 
Create Date: 2026-06-27 14:16:38.368455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24bc4ea98b96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'EXPERT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notification_prefs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('industry', sa.Enum('OIL_GAS', 'PETROCHEMICAL', 'STEEL', 'MINING', 'INFRASTRUCTURE', 'OTHER', name='industry'), nullable=True),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='orgsize'), nullable=True),
    sa.Column('priority_level', sa.Enum('A_STRATEGIC', 'B_MEDIUM', 'C_GENERAL', name='prioritylevel'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('relationship_status', sa.Enum('CURRENT_CLIENT', 'FORMER_CLIENT', 'NEW_LEAD', 'COMPETITOR', name='relationshipstatus'), nullable=True),
    sa.Column('account_manager_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='auditaction'), nullable=False),
    sa.Column('changed_by_id', sa.String(), nullable=False),
    sa.Column('change_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('OVERDUE_FOLLOWUP', 'UPCOMING_FOLLOWUP', 'AT_RISK_OPPORTUNITY', 'PENDING_WIN_LOSS', 'STAGE_CHANGE', 'NEW_ASSIGNMENT', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('direct_line', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('influence_level', sa.Enum('DECISION_MAKER', 'TECHNICAL_INFLUENCER', 'BLOCKER', 'BUYER', name='influencelevel'), nullable=True),
    sa.Column('sentiment', sa.Enum('CHAMPION', 'NEUTRAL', 'OPPONENT', name='sentiment'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('project_type', sa.Enum('EPC', 'EQUIPMENT_SUPPLY', 'CONSULTING', 'SUPPORT', name='projecttype'), nullable=True),
    sa.Column('sales_stage', sa.Enum('INITIAL_CONTACT', 'NEEDS_ASSESSMENT', 'PROPOSAL_SENT', 'NEGOTIATION', 'CONTRACT_SIGNED', 'CLOSED_WON', 'CLOSED_LOST', 'ABANDONED', name='salesstage'), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('lead_source', sa.Enum('TENDER', 'COLD_CALL', 'REFERRAL', 'CONFERENCE', 'WEBSITE', name='leadsource'), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('competitors', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('assigned_to_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('activity_type', sa.Enum('IN_PERSON_MEETING', 'PHONE_CALL', 'SITE_VISIT', 'PROPOSAL_SENT', 'EMAIL', name='activitytype'), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('next_step', sa.String(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('follow_up_completed', sa.Boolean(), nullable=False),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_stage_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('from_stage', sa.Enum('INITIAL_CONTACT', 'NEEDS_ASSESSMENT', 'PROPOSAL_SENT', 'NEGOTIATION', 'CONTRACT_SIGNED', 'CLOSED_WON', 'CLOSED_LOST', 'ABANDONED', name='salesstage'), nullable=True),
    sa.Column('to_stage', sa.Enum('INITIAL_CONTACT', 'NEEDS_ASSESSMENT', 'PROPOSAL_SENT', 'NEGOTIATION', 'CONTRACT_SIGNED', 'CLOSED_WON', 'CLOSED_LOST', 'ABANDONED', name='salesstage'), nullable=False),
    sa.Column('changed_by_id', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win_loss_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('final_status', sa.Enum('WON', 'LOST', 'ABANDONED', name='finalstatus'), nullable=False),
    sa.Column('result_reason', sa.Enum('PRICE', 'TECHNOLOGY', 'RELATIONSHIPS', 'TIMING', 'NO_GO', 'OTHER', name='resultreason'), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('final_contract_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('analyzed_by_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('win_loss_analysis')
    op.drop_table('opportunity_stage_history')
    op.drop_table('activities')
    op.drop_table('opportunities')
    op.drop_table('contacts')
    op.drop_table('notifications')
    op.drop_table('audit_logs')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
